---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jupyterhub
spec:
  replicas: 1
  selector:
    app: jupyterhub
  template:
    metadata:
      labels:
        app: jupyterhub
      name: jupyterhub
    spec:
      containers:
        - 
          image: "jupyterhub/jupyterhub"
          imagePullPolicy: Always
          name: jupyterhub
          ports:
            - 
              containerPort: 8000
              hostPort: 80
